version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app  # Für Hot-Reloading
      - storage:/app/storage
    environment:
      - ENVIRONMENT=development
      - LOG_LEVEL=DEBUG
      - MAX_WORKERS=1
      - ENABLE_METRICS=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: unless-stopped

volumes:
  storage:  # Persistentes Volume für Upload-Dateien 